#!/bin/bash -l
##SBATCH -o ./tjob.out.%j
##SBATCH -e ./tjob.err.%j
##SBATCH -D ./
#SBATCH -J chg_Na_FS
##SBATCH --partition=medium
#SBATCH --nodes=12
#SBATCH --ntasks-per-node=40
#SBATCH --mail-type=all
#SBATCH --mail-user=teosfp@hotmail.com
#SBATCH --time=2:30:00

# Run the program:
module          unload intel mkl impi
module          load intel/19.1.3
module          load mkl/2019.5
module          load impi/2019.9
export VASP_HOME=/u/trahman/shared/apps/vasp/5.4.4_tpot9/bin/

cd foler_with_inputs
srun $VASP_HOME/vasp_gam_tpot > out
cd ..
cd foler_with_inputs
srun $VASP_HOME/vasp_gam_tpot > out
cd ..
cd foler_with_inputs
srun $VASP_HOME/vasp_gam_tpot > out
cd ..

