#!/bin/bash -l
##SBATCH -o ./tjob.out.%j
##SBATCH -e ./tjob.err.%j
##SBATCH -D ./
#SBATCH -J name
##SBATCH --partition=n0064
#SBATCH --nodes=64
#SBATCH --ntasks-per-node=40
#SBATCH --mail-type=all
#SBATCH --mail-user=teosfp@hotmail.com
#SBATCH --time=24:00:00

# Run the program:
#module unload vasp
#module load vasp/5.4.4_sol
#srun vasp_gam_tpot2 > out


module          unload intel mkl impi
module          load intel/19.1.3
module          load mkl/2019.5
module          load impi/2019.9
export VASP_HOME=/u/trahman/shared/apps/vasp/5.4.4_sol
export loc=/cobra/u/trahman/data/theo/Bi/CH3_4N/CH3_4N_side

npj=16
nrpj=640

cd $loc/FindChg_0.0/target_potential/; srun -N ${npj} -n ${nrpj} $VASP_HOME/bin/vasp_gam_tpot2 > out &
cd $loc/FindChg_-0.5/target_potential/; srun -N ${npj} -n ${nrpj} $VASP_HOME/bin/vasp_gam_tpot2 > out &
cd $loc/FindChg_-1.0/target_potential/; srun -N ${npj} -n ${nrpj} $VASP_HOME/bin/vasp_gam_tpot2 > out &
cd $loc/FindChg_-1.2/target_potential/; srun -N ${npj} -n ${nrpj} $VASP_HOME/bin/vasp_gam_tpot2 > out &

wait
